const user=[{
    "id": 1,
    "username": "msindle0",
    "password": "Xn0k6xFF",
    "firstname": "Mair",
    "lastname": "Sindle",
    "email": "msindle0@geocities.jp"
  }, {
    "id": 2,
    "username": "tkingston1",
    "password": "oMsesXLKEN1n",
    "firstname": "Terrill",
    "lastname": "Kingston",
    "email": "tkingston1@fotki.com"
  }, {
    "id": 3,
    "username": "easy",
    "password": "easy",
    "firstname": "Sacha",
    "lastname": "Landeg",
    "email": "slandeg2@toplist.cz"
  }, {
    "id": 4,
    "username": "rmingauld3",
    "password": "79Eo0C4LY3f",
    "firstname": "Rosene",
    "lastname": "Mingauld",
    "email": "rmingauld3@cnn.com"
  }, {
    "id": 5,
    "username": "mdurling4",
    "password": "MiRkap",
    "firstname": "Marthena",
    "lastname": "Durling",
    "email": "mdurling4@hibu.com"
  }, {
    "id": 6,
    "username": "ksuche5",
    "password": "z1QLhQBQRe",
    "firstname": "Kary",
    "lastname": "Suche",
    "email": "ksuche5@google.cn"
  }, {
    "id": 7,
    "username": "lruprechter6",
    "password": "SbrUS3",
    "firstname": "Lisetta",
    "lastname": "Ruprechter",
    "email": "lruprechter6@guardian.co.uk"
  }, {
    "id": 8,
    "username": "kcraggs7",
    "password": "0EUbx56toojK",
    "firstname": "Kizzie",
    "lastname": "Craggs",
    "email": "kcraggs7@washington.edu"
  }, {
    "id": 9,
    "username": "mdaintree8",
    "password": "LFy4Fccwur8",
    "firstname": "Marketa",
    "lastname": "Daintree",
    "email": "mdaintree8@wikipedia.org"
  }, {
    "id": 10,
    "username": "peade9",
    "password": "SOt76obrg6dk",
    "firstname": "Patricio",
    "lastname": "Eade",
    "email": "peade9@cafepress.com"
  }, {
    "id": 11,
    "username": "swhatlinga",
    "password": "gD21Rs9G",
    "firstname": "Stephanus",
    "lastname": "Whatling",
    "email": "swhatlinga@dagondesign.com"
  }, {
    "id": 12,
    "username": "mroydonb",
    "password": "xT4VYyht",
    "firstname": "Meryl",
    "lastname": "Roydon",
    "email": "mroydonb@bloglines.com"
  }, {
    "id": 13,
    "username": "spiwellc",
    "password": "JFAd5A3kB2tX",
    "firstname": "Skelly",
    "lastname": "Piwell",
    "email": "spiwellc@youtube.com"
  }, {
    "id": 14,
    "username": "khalshawd",
    "password": "7koMODIbU4Im",
    "firstname": "Katina",
    "lastname": "Halshaw",
    "email": "khalshawd@washingtonpost.com"
  }, {
    "id": 15,
    "username": "pkernese",
    "password": "0GiNI0CHQ",
    "firstname": "Peg",
    "lastname": "Kernes",
    "email": "pkernese@cdc.gov"
  }, {
    "id": 16,
    "username": "msaytonf",
    "password": "mtDMBKoK0",
    "firstname": "Micki",
    "lastname": "Sayton",
    "email": "msaytonf@google.com.au"
  }, {
    "id": 17,
    "username": "kjulianog",
    "password": "jWX7i1rwc",
    "firstname": "Katina",
    "lastname": "Juliano",
    "email": "kjulianog@chicagotribune.com"
  }, {
    "id": 18,
    "username": "dmcgaugeyh",
    "password": "xqD7oqx",
    "firstname": "Dode",
    "lastname": "McGaugey",
    "email": "dmcgaugeyh@senate.gov"
  }, {
    "id": 19,
    "username": "slapthornei",
    "password": "9MgHU1",
    "firstname": "Sonia",
    "lastname": "Lapthorne",
    "email": "slapthornei@wix.com"
  }, {
    "id": 20,
    "username": "dwylliej",
    "password": "jXUNX9AXts",
    "firstname": "Dmitri",
    "lastname": "Wyllie",
    "email": "dwylliej@hud.gov"
  }];

  export default user;